#!/usr/bin/env python3

import os

import rclpy
from rclpy.node import Node
from tf2_msgs.msg import TFMessage
from geometry_msgs.msg import TransformStamped, Transform
import ament_index_python

from rosbags.rosbag1 import Reader
from rosbags.serde import deserialize_cdr, ros1_to_cdr
from rosbags.typesys import get_types_from_msg, register_types

from quadrotor_simulator_py.quadrotor_model import QuadrotorModel


def get_pose_rpm_messages(bagfilepath):
    typs = {}
    reader = None
    with Reader(bagfilepath) as reader:
        for conn in reader.connections:
            typs.update(get_types_from_msg(conn.msgdef, conn.msgtype))
            register_types(typs)

    reader.open()
    msgs = []
    connections = [
        x for x in reader.connections if (x.topic == "quadrotor_msgs/msg/StateSpace")]

    for idx, (connection, timestamp, rawdata) in enumerate(reader.messages(connections=connections)):
        msgs.append(deserialize_cdr(ros1_to_cdr(
            rawdata, connection.msgtype), connection.msgtype))

    return msgs


def to_sec(header):
    return header.stamp.sec + header.stamp.nanosec*1e-9


def extract_time(msg):
    return to_sec(msg.header)


def sort_messages(msgsin):

    # First check to see if the messages are in order
    msgsout = []
    for msg in msgsin:
        if msg.__msgtype__ == 'quadrotor_msgs/msg/StateSpace':
            msgsout.append(msg)
    msgsout.sort(key=extract_time)
    return msgsout


class QuadrotorSimulatorNode(Node):
    def __init__(self):
        super().__init__('quadrotor_simulator_node')

        # initialize TF frames
        self.fixed_frame_id = 'world'
        self.base_frame_id = 'body'

        # initialize Quadrotor Model
        self.model = QuadrotorModel()
        model_config_file = os.path.join(ament_index_python.get_package_share_directory(
            'quadrotor_simulator_py'), 'config/rocky0704_model_params.yaml')
        self.model.initialize(model_config_file)

        # create odom and transform publishers
        self.tf_pub = self.create_publisher(TFMessage, "/tf", 10)

        # Load bagfile
        cwd = os.getcwd()
        bagfilepath = None
        bagfilename = "room_2023-05-22-13-29-19.bag"
        sandbox = "quadrotor_simulator_ws"
        if sandbox in cwd:
            bagfilepath = cwd.split(sandbox)
            bagfilepath = bagfilepath[0] + sandbox + "/data/" + bagfilename
            self.get_logger().info(bagfilepath)
        else:
            raise Exception(
                "quadrotor_simulator_ws not found in current path.")

        # read the messages from the bag file in sorted order
        msgs = get_pose_rpm_messages(bagfilepath)
        sorted_msgs = sort_messages(msgs)

        for msg in sorted_msgs:
            if msg.__msgtype__ == 'quadrotor_msgs/msg/StateSpace':
                ts = TransformStamped()
                ts.transform = Transform()

                uRPM = msg.rotor_speeds.tolist()
                self.model.apply_command(uRPM)
                self.model.update(to_sec(msg.header))
                Twb = self.model.get_pose()

                translation = Twb.translation()
                ts.transform.translation.x = translation[0]
                ts.transform.translation.y = translation[1]
                ts.transform.translation.z = translation[2]

                quaternion = Twb.quaternion()
                ts.transform.rotation.w = quaternion[0]
                ts.transform.rotation.x = quaternion[1]
                ts.transform.rotation.y = quaternion[2]
                ts.transform.rotation.z = quaternion[3]

                ts.header.stamp = self.get_clock().now().to_msg()
                ts.header.frame_id = self.fixed_frame_id
                ts.child_frame_id = self.base_frame_id

                tf_msg = TFMessage(transforms=[ts])
                self.tf_pub.publish(tf_msg)


def main(args=None):
    rclpy.init(args=args)

    qsimnode = QuadrotorSimulatorNode()

    rclpy.spin(qsimnode)


if __name__ == '__main__':
    main()
